logging:
  project: world_model_evaluation
  entity: null
  run_name: exp_jit_19500_95rollout_5steps_train
  output_dir: "/checkpoints"
  log_interval: 1
  signal_level_log_limit: 100
  checkpoint_interval: 0

checkpoint_path: /gpfs/helios/home/gauthierbernarda/git/World-Model/checkpoints/exp_jit/world_model_step_019500.pt

evaluator:
  video_sample_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  rollout_start_frame: 6
  rollout_signal_level: 0.95
  precision: bf16
  max_batches: 10
  denoising_metrics_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] # List of diffusion steps to capture intermediates for (first sequence, first frame only)
  save_denoising_frames: false

eval_dataset:
  sequence_length_distribution:
    "40": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    droid: 1.0
  reference_dataset: droid
  datasets:
    droid:
      type: lerobot
      repo_id: aractingi/droid_1.0.1
      episodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      excluded_episodes: null
      episode_midpoint_only: true
      cameras:
        observation.images.exterior_1_left: 1.0
        # observation.images.exterior_2_left: 1.0
        # observation.images.wrist_left: 1.0
      action_normalization: null
      independent_frames_probability: 0.0
      use_action_probability: 1.0
      action_mode: endeffector

eval_dataloader:
  batch_size: 12
  shuffle: false
  num_workers: 0
  pin_memory: true

signal_scheduler:
  mode: "logit_normal"  # {"resolution_shift", "linear_shift", "uniform", "logit_normal"}
  min_value: 0.0
  max_value: 1.0


euler_solver:
  number_steps: 5
  min_denom: 0.05
  timestep_schedule: "linear"

world_model:
  input_dim: 768
  latent_dim: 768
  bottleneck_dim: 128
  action_dim: 7
  num_registers: 4
  depth: 15
  num_heads: 12
  mlp_multiplier: 4.0
  temporal_attention_interval: 4
  temporal_context_length: 15
  rope_base: 10000.0
  qk_norm_eps: 1.0e-06
  attn_logit_softcapping: 50.0
