logging:
  project: world_model
  entity: null
  run_name: soar_bottleneck
  output_dir: checkpoints
  log_interval: 1
  signal_level_log_limit: 100
  checkpoint_interval: 500

trainer:
  loss_type: velocity
  loss_weighting: null
  loss_weighting_intercept: 0.1
  loss_weighting_slope: 0.9
  evaluation_interval: 500
  grad_accum_steps: 8
  precision: bf16
  seed: 3
  resume: false
  load_checkpoint: null

evaluator:
  video_sample_indices: [0, 1, 2, 3, 4, 5, 6, 7]
  rollout_start_frame: 6
  rollout_signal_level: 0.9
  precision: bf16
  max_batches: 10
  denoising_metrics_indices: [0, 1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 96, 97, 98, 99]
  save_denoising_frames: false

optimizer:
  lr:
    "0": 1.0e-7
    "1000": 3.0e-4

  eps: 1.0e-08
  grad_clip_norm: 1.0
  weight_decay: 0.01

ema:
  enabled: false
  decay: 0.9995
  start_step: 5000

train_dataloader:
  batch_size: 256
  shuffle: true
  num_workers: 6
  pin_memory: true

train_dataset:
  sequence_length_distribution:
    "23": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    soar: 1.0
  reference_dataset: soar
  datasets:
    soar:
      type: lerobot
      repo_id: Gaugou/Soar
      episodes: null
      excluded_episodes: null
      episode_midpoint_only: false
      cameras:
        observation.images.image: 1.0
      action_mode: soar_relative_ee_normalized
      independent_frames_probability: 0.3
      use_action_probability: 1.0

eval_dataloader:
  batch_size: 8
  shuffle: false
  num_workers: 0
  pin_memory: false

eval_dataset:
  sequence_length_distribution:
    "90": 1.0
  fps: 5.0
  action_dim: 7
  weights:
    soar: 1.0
  reference_dataset: soar
  datasets:
    soar:
      type: lerobot
      repo_id: Gaugou/Soar
      episodes: [0, 50, 500, 5000, 1000, 10000, 15000, 20000]
      excluded_episodes: null
      episode_midpoint_only: true
      cameras:
        observation.images.image: 1.0
      action_mode: soar_relative_ee_normalized
      independent_frames_probability: 0.0
      use_action_probability: 1.0

signal_scheduler:
  mode: "logit_normal"  # {"resolution_shift", "linear_shift", "uniform", "logit_normal"}
  min_value: 0.0
  max_value: 1.0
  logit_normal_loc: -0.8
  logit_normal_scale: 0.8

euler_solver:
  number_steps: 50
  min_denom: 0.05
  timestep_schedule: "linear"

world_model: # ~400M parameters
  input_dim: 768
  latent_dim: 1536
  bottleneck_dim: 64
  action_dim: 7
  num_registers: 4
  depth: 28
  num_heads: 24
  mlp_multiplier: 2.666667
  temporal_attention_interval: 4
  temporal_context_length: 18
  rope_base: 10000.0
  qk_norm_eps: 1.0e-06
  attn_logit_softcapping: 50.0 # None for no softcapping -> able to use fused_attention